name: Storybook Test
description: Storybook Test

runs:
  using: 'composite'
  steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      # https://github.com/swc-project/swc/issues/5616
      # TODO: GitHub actionsのswc/coreのみをインストールする
      - name: Install swc
        shell: bash
        run: |
          yarn add \
           "@swc/core-linux-arm-gnueabihf" \
           "@swc/core-linux-arm64-gnu" \
           "@swc/core-linux-arm64-musl" \
           "@swc/core-linux-x64-gnu" \
           "@swc/core-linux-x64-musl --optional --save-optional"
      - name: storybook build
        run: yarn rw storybook --build
        shell: bash
      - name: storybook test
        run: |
          cd web
          yarn test-storybook:ci
          cd ..
        shell: bash
