name: storybook_test

on: [push]

jobs:
  storybook_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: StorybookTest
        uses: ./.github/actions/sbtest
